name: Deploy to Google Cloud

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy (ignore cache)'
        required: false
        default: 'false'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
  API_SERVICE_NAME: inventory-api
  CLIENT_SERVICE_NAME: inventory-client
  REGION: asia-east1

jobs:
  deploy-api:
    name: 'Deploy API to Cloud Run'
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify Authentication'
        run: |-
          echo "🔍 驗證 GCP 認證..."
          gcloud auth list --filter=status:ACTIVE --format="value(account)" || exit 1
          echo "✅ 認證成功"
          
          echo "🔍 驗證專案存取權限..."
          gcloud projects describe ${{ env.PROJECT_ID }} --format="value(name)" || exit 1
          echo "✅ 專案存取權限正常"
          
          echo "🔍 驗證 Artifact Registry 存取權限..."
          gcloud artifacts repositories list --location=${{ env.REGION }} --format="value(name)" || exit 1
          echo "✅ Artifact Registry 存取權限正常"
          
          echo "🔍 驗證 Secret Manager 存取權限..."
          gcloud secrets versions access latest --secret="LARAVEL_APP_KEY" >/dev/null || exit 1
          gcloud secrets versions access latest --secret="LARAVEL_DB_PASSWORD" >/dev/null || exit 1
          echo "✅ Secret Manager 存取權限正常"
          
          echo "🔍 驗證 Compute Engine 預設服務帳號 Secret Manager 權限..."
          gcloud projects get-iam-policy ${{ env.PROJECT_ID }} \
            --flatten="bindings[].members" \
            --filter="bindings.members:672374290013-compute@developer.gserviceaccount.com AND bindings.role:roles/secretmanager.secretAccessor" \
            --format="value(bindings.role)" | grep -q "roles/secretmanager.secretAccessor" || {
              echo "❌ Compute Engine 預設服務帳號缺少 Secret Manager 權限"
              echo "請執行：gcloud projects add-iam-policy-binding ${{ env.PROJECT_ID }} \\"
              echo "  --member='serviceAccount:672374290013-compute@developer.gserviceaccount.com' \\"
              echo "  --role='roles/secretmanager.secretAccessor'"
              exit 1
            }
          echo "✅ Compute Engine 預設服務帳號 Secret Manager 權限正常"
          
          echo "🔍 驗證 Cloud SQL 連線名稱格式..."
          CONN_NAME="${{ env.CLOUD_SQL_CONNECTION_NAME }}"
          echo "Cloud SQL 連線名稱長度: ${#CONN_NAME}"
          echo "前 10 個字元: ${CONN_NAME:0:10}..."
          echo "包含冒號數量: $(echo "$CONN_NAME" | tr -cd ':' | wc -c)"
          
          if [[ "$CONN_NAME" =~ ^[^:]+:[^:]+:[^:]+$ ]]; then
            echo "✅ Cloud SQL 連線名稱格式正確"
            # 顯示各部分（遮蔽部分內容）
            IFS=':' read -r PROJECT REGION INSTANCE <<< "$CONN_NAME"
            echo "   專案 ID: ${PROJECT:0:8}..."
            echo "   區域: $REGION"
            echo "   實例名稱: $INSTANCE"
          else
            echo "❌ Cloud SQL 連線名稱格式錯誤"
            echo "預期格式: PROJECT_ID:REGION:INSTANCE_NAME"
            echo "例如: turnkey-pottery-461707-b5:asia-east1:lomis-db-instance"
            echo "實際值: $CONN_NAME"
            exit 1
          fi
          
          echo "🔍 驗證 Cloud SQL 實例存在..."
          gcloud sql instances describe lomis-db-instance --project=${{ env.PROJECT_ID }} >/dev/null || {
            echo "❌ Cloud SQL 實例 'lomis-db-instance' 不存在"
            exit 1
          }
          echo "✅ Cloud SQL 實例存在"
          
          echo "🔍 驗證環境變數完整性..."
          [ -z "${{ env.PROJECT_ID }}" ] && echo "❌ PROJECT_ID 未設定" && exit 1
          [ -z "${{ env.GCS_BUCKET }}" ] && echo "❌ GCS_BUCKET 未設定" && exit 1
          [ -z "${{ env.CLOUD_SQL_CONNECTION_NAME }}" ] && echo "❌ CLOUD_SQL_CONNECTION_NAME 未設定" && exit 1
          [ -z "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" ] && echo "❌ GCP_WORKLOAD_IDENTITY_PROVIDER 未設定" && exit 1
          [ -z "${{ secrets.GCP_SERVICE_ACCOUNT }}" ] && echo "❌ GCP_SERVICE_ACCOUNT 未設定" && exit 1
          echo "✅ 所有必要環境變數已設定"
          
          echo "🔍 驗證 GCS Bucket 存在且可存取..."
          gsutil ls -b gs://${{ env.GCS_BUCKET }} >/dev/null || {
            echo "❌ GCS Bucket '${{ env.GCS_BUCKET }}' 不存在或無法存取"
            exit 1
          }
          echo "✅ GCS Bucket 存在且可存取"
          
          echo "🔍 驗證資料庫存在..."
          gcloud sql databases describe lomis_internal --instance=lomis-db-instance --project=${{ env.PROJECT_ID }} >/dev/null || {
            echo "❌ 資料庫 'lomis_internal' 不存在於實例 'lomis-db-instance'"
            echo "請執行：gcloud sql databases create lomis_internal --instance=lomis-db-instance"
            exit 1
          }
          echo "✅ 資料庫存在"
          
          echo "🔍 驗證 Artifact Registry 倉庫..."
          gcloud artifacts repositories describe ${{ env.API_SERVICE_NAME }}-repo --location=${{ env.REGION }} >/dev/null 2>&1 || {
            echo "⚠️ Artifact Registry 倉庫 '${{ env.API_SERVICE_NAME }}-repo' 不存在，將在構建時創建"
          }
          
          echo "🔍 驗證 Cloud Run 服務名稱規範..."
          if [[ ! "${{ env.API_SERVICE_NAME }}" =~ ^[a-z][a-z0-9-]{0,62}$ ]]; then
            echo "❌ API 服務名稱 '${{ env.API_SERVICE_NAME }}' 不符合 Cloud Run 命名規範"
            echo "服務名稱必須以小寫字母開頭，只能包含小寫字母、數字和連字符"
            exit 1
          fi
          if [[ ! "${{ env.CLIENT_SERVICE_NAME }}" =~ ^[a-z][a-z0-9-]{0,62}$ ]]; then
            echo "❌ Client 服務名稱 '${{ env.CLIENT_SERVICE_NAME }}' 不符合 Cloud Run 命名規範"
            exit 1
          fi
          echo "✅ 服務名稱符合規範"
          
          echo "🔍 驗證 Workload Identity 配置..."
          # 從 provider 中提取 pool 名稱
          POOL_NAME=$(echo "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" | sed -n 's|projects/.*/locations/.*/workloadIdentityPools/\([^/]*\)/.*|\1|p')
          if [ -n "$POOL_NAME" ]; then
            gcloud iam workload-identity-pools describe "$POOL_NAME" --location=global --project=${{ env.PROJECT_ID }} >/dev/null || {
              echo "❌ Workload Identity Pool 不存在或無法存取"
              exit 1
            }
            echo "✅ Workload Identity 配置正確"
          else
            echo "⚠️ 無法解析 Workload Identity Provider，跳過驗證"
          fi

      - name: 'Get Client URL for CORS'
        id: get_client_url
        run: |-
          # 優先使用自訂網域（如果有設定）
          if [ ! -z "${{ secrets.CLIENT_CUSTOM_DOMAIN_URL }}" ]; then
            echo "CLIENT_URL=${{ secrets.CLIENT_CUSTOM_DOMAIN_URL }}" >> $GITHUB_OUTPUT
            echo "使用客戶端自訂網域: ${{ secrets.CLIENT_CUSTOM_DOMAIN_URL }}"
          else
            # 使用預設的 Cloud Run URL
            echo "CLIENT_URL=https://${{ env.CLIENT_SERVICE_NAME }}-${{ secrets.GCP_SERVICE_ID }}-${{ env.REGION }}.a.run.app" >> $GITHUB_OUTPUT
            echo "使用預設 Cloud Run URL"
          fi

      - name: 'Build and Test API Docker Image'
        run: |-
          gcloud artifacts repositories create ${{ env.API_SERVICE_NAME }}-repo \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --description="API Docker repository" || echo "Repo already exists"
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          
          echo "🔨 構建 Docker 映像..."
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest ./inventory-api
          
          echo "🧪 測試容器啟動..."
          # 測試容器是否能在 8080 端口啟動（模擬 Cloud Run 環境）
          docker run -d --name test-api-container \
            -p 8080:8080 \
            -e PORT=8080 \
            -e APP_ENV=testing \
            -e APP_KEY=base64:dGVzdGluZ0tleUZvckRvY2tlcg== \
            -e DB_CONNECTION=sqlite \
            -e DB_DATABASE=:memory: \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest
          
          echo "⏳ 等待容器啟動..."
          sleep 30
          
          echo "🔍 檢查容器健康狀態..."
          if docker exec test-api-container curl -f http://localhost:8080/api/health; then
            echo "✅ 容器啟動成功並響應健康檢查"
          else
            echo "❌ 容器啟動失敗或健康檢查失敗"
            echo "📋 容器日誌："
            docker logs test-api-container
            docker rm -f test-api-container
            exit 1
          fi
          
          echo "🧹 清理測試容器..."
          docker rm -f test-api-container
          
          echo "📤 推送 Docker 映像..."
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest

      - name: 'Deploy API to Cloud Run'
        run: |-
          gcloud run deploy ${{ env.API_SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --add-cloudsql-instances=turnkey-pottery-461707-b5:asia-east1:lomis-db-instance \
            --set-env-vars="APP_ENV=production,APP_NAME=庫存管理系統,APP_DEBUG=false,APP_TIMEZONE=Asia/Taipei,APP_LOCALE=zh_TW,APP_FALLBACK_LOCALE=zh_TW,BCRYPT_ROUNDS=12,APP_MAINTENANCE_DRIVER=file,DB_CONNECTION=mysql,DB_SOCKET=/cloudsql/${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance,DB_PORT=3306,DB_DATABASE=lomis_internal,DB_USERNAME=h1431532403240,FRONTEND_URL=${{ steps.get_client_url.outputs.CLIENT_URL }},SESSION_DOMAIN=.lomis.com.tw,SESSION_DRIVER=file,SESSION_LIFETIME=120,SESSION_ENCRYPT=false,SESSION_PATH=/,SANCTUM_STATEFUL_DOMAINS=www.lomis.com.tw,FILESYSTEM_DISK=gcs,GCS_BUCKET=${{ env.GCS_BUCKET }},GOOGLE_CLOUD_PROJECT_ID=${{ env.PROJECT_ID }},CACHE_STORE=file,QUEUE_CONNECTION=sync,BROADCAST_CONNECTION=log,LOG_CHANNEL=stack,LOG_LEVEL=error,SPATIE_PERMISSION_CACHE_EXPIRATION_TIME=3600" \
            --set-secrets="LARAVEL_APP_KEY=LARAVEL_APP_KEY:latest,LARAVEL_DB_PASSWORD=LARAVEL_DB_PASSWORD:latest" \
            --timeout=300 \
            --memory=1Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=3
            
      - name: 'Update API URL Environment Variable'
        run: |-
          echo "更新 API URL 環境變數..."
          API_URL=$(gcloud run services describe ${{ env.API_SERVICE_NAME }} --platform=managed --region=${{ env.REGION }} --format='value(status.url)')
          gcloud run services update ${{ env.API_SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --update-env-vars="APP_URL=${API_URL}"

      - name: 'Run Database Migrations'
        run: |-
          echo "創建或更新資料庫遷移 Job..."
          if gcloud run jobs describe ${{ env.API_SERVICE_NAME }}-migrate --region=${{ env.REGION }} >/dev/null 2>&1; then
            echo "刪除現有的遷移 Job（重新創建以更新配置）..."
            gcloud run jobs delete ${{ env.API_SERVICE_NAME }}-migrate --region=${{ env.REGION }} --quiet
          fi
          
          echo "創建新的遷移 Job..."
          gcloud run jobs create ${{ env.API_SERVICE_NAME }}-migrate \
            --region=${{ env.REGION }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest \
            --command=/usr/local/bin/migrate-entrypoint.sh \
            --set-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance \
            --set-env-vars="APP_ENV=production,APP_NAME=庫存管理系統,APP_DEBUG=false,APP_TIMEZONE=Asia/Taipei,APP_LOCALE=zh_TW,APP_FALLBACK_LOCALE=zh_TW,BCRYPT_ROUNDS=12,DB_CONNECTION=mysql,DB_SOCKET=/cloudsql/${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance,DB_PORT=3306,DB_DATABASE=lomis_internal,DB_USERNAME=h1431532403240,CACHE_STORE=file,LOG_CHANNEL=stack,LOG_LEVEL=debug,GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }},INSTANCE_CONNECTION_NAME=${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance,INITIAL_ADMIN_USERNAME=${{ secrets.INITIAL_ADMIN_USERNAME || 'admin' }},INITIAL_ADMIN_PASSWORD=${{ secrets.INITIAL_ADMIN_PASSWORD }},INITIAL_ADMIN_NAME=${{ secrets.INITIAL_ADMIN_NAME || '系統管理員' }}" \
            --set-secrets="LARAVEL_APP_KEY=LARAVEL_APP_KEY:latest,LARAVEL_DB_PASSWORD=LARAVEL_DB_PASSWORD:latest" \
            --task-timeout=600 \
            --cpu=1 \
            --memory=1Gi \
            --parallelism=1 \
            --max-retries=1
          
          echo "執行資料庫遷移..."
          gcloud run jobs execute ${{ env.API_SERVICE_NAME }}-migrate --region=${{ env.REGION }} --wait

      - name: 'Generate OpenAPI using Cloud Run Jobs'
        id: generate_openapi
        run: |-
          echo "📄 使用 Cloud Run Jobs 生成 OpenAPI..."
          
          # 建立或更新 OpenAPI 生成 Job
          gcloud run jobs create ${{ env.API_SERVICE_NAME }}-openapi \
            --region=${{ env.REGION }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.API_SERVICE_NAME }}-repo/api:latest \
            --command=/usr/local/bin/openapi-entrypoint.sh \
            --set-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance \
            --set-env-vars="APP_ENV=production,APP_NAME=庫存管理系統,APP_DEBUG=false,APP_TIMEZONE=Asia/Taipei,APP_LOCALE=zh_TW,APP_FALLBACK_LOCALE=zh_TW,BCRYPT_ROUNDS=12,DB_CONNECTION=mysql,DB_SOCKET=/cloudsql/${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance,DB_PORT=3306,DB_DATABASE=lomis_internal,DB_USERNAME=h1431532403240,CACHE_STORE=file,LOG_CHANNEL=stack,LOG_LEVEL=debug,GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }},INSTANCE_CONNECTION_NAME=${{ env.PROJECT_ID }}:${{ env.REGION }}:lomis-db-instance,GCS_BUCKET=${{ env.GCS_BUCKET }}" \
            --set-secrets="LARAVEL_APP_KEY=LARAVEL_APP_KEY:latest,LARAVEL_DB_PASSWORD=LARAVEL_DB_PASSWORD:latest" \
            --task-timeout=300 \
            --cpu=1 \
            --memory=1Gi \
            --parallelism=1 \
            --max-retries=1 \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }} || echo "Job already exists"
          
          # 執行 Job
          echo "執行 OpenAPI 生成 Job..."
          gcloud run jobs execute ${{ env.API_SERVICE_NAME }}-openapi --region=${{ env.REGION }} --wait
          
          # 從 GCS 下載生成的 OpenAPI
          echo "從 GCS 下載 OpenAPI..."
          gsutil cp gs://${{ env.GCS_BUCKET }}/openapi/openapi-latest.yaml ./openapi-generated.yaml
          
          # 驗證生成的檔案
          if [ -f ./openapi-generated.yaml ]; then
            echo "✅ OpenAPI 檔案已生成"
            echo "檔案大小：$(wc -l < ./openapi-generated.yaml) 行"
            if [ $(wc -l < ./openapi-generated.yaml) -lt 100 ]; then
              echo "❌ OpenAPI 檔案太小，可能不完整"
              cat ./openapi-generated.yaml
              exit 1
            fi
          else
            echo "❌ 無法下載 OpenAPI 檔案"
            exit 1
          fi

      - name: 'Upload OpenAPI Specification'
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: ./openapi-generated.yaml
          if-no-files-found: error

  deploy-client:
    name: 'Deploy Client to Cloud Run'
    needs: deploy-api
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify Authentication'
        run: |-
          echo "🔍 驗證 GCP 認證（Client 部署）..."
          gcloud auth list --filter=status:ACTIVE --format="value(account)" || exit 1
          echo "✅ Client 部署認證正常"
        
      - name: 'Determine API URL'
        id: get_api_url
        run: |-
          # 優先使用自訂網域（如果有設定）
          if [ ! -z "${{ secrets.API_CUSTOM_DOMAIN_URL }}" ]; then
            echo "API_URL=${{ secrets.API_CUSTOM_DOMAIN_URL }}" >> $GITHUB_OUTPUT
            echo "使用自訂網域: ${{ secrets.API_CUSTOM_DOMAIN_URL }}"
          else
            # 如果沒有自訂網域，則使用 Cloud Run 自動生成的 URL
            API_URL=$(gcloud run services describe ${{ env.API_SERVICE_NAME }} --platform=managed --region=${{ env.REGION }} --format='value(status.url)')
            echo "API_URL=${API_URL}" >> $GITHUB_OUTPUT
            echo "使用 Cloud Run URL: ${API_URL}"
          fi

      - name: 'Download OpenAPI Specification'
        uses: actions/download-artifact@v4
        with:
          name: openapi-spec
          path: ./

      - name: 'Prepare OpenAPI for Frontend'
        run: |-
          echo "📄 準備 OpenAPI 規格..."
          if [ -f ./openapi-generated.yaml ]; then
            echo "✅ 找到從 API 服務下載的 OpenAPI 規格"
            cp ./openapi-generated.yaml ./inventory-client/openapi.yaml
            ls -la ./inventory-client/openapi.yaml
            echo "檔案大小：$(wc -l < ./inventory-client/openapi.yaml) 行"
            # 顯示前幾行以確認內容
            echo "檔案開頭內容："
            head -20 ./inventory-client/openapi.yaml
          else
            echo "❌ 無法找到 OpenAPI 規格"
            exit 1
          fi

      - name: 'Build and Push Client Docker Image'
        run: |-
          gcloud artifacts repositories create ${{ env.CLIENT_SERVICE_NAME }}-repo \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --description="Client Docker repository" || echo "Repo already exists"
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          docker build --build-arg NEXT_PUBLIC_API_BASE_URL=${{ steps.get_api_url.outputs.API_URL }} -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CLIENT_SERVICE_NAME }}-repo/client:latest ./inventory-client
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CLIENT_SERVICE_NAME }}-repo/client:latest

      - name: 'Deploy Client to Cloud Run'
        run: |-
          gcloud run deploy ${{ env.CLIENT_SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CLIENT_SERVICE_NAME }}-repo/client:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars="NEXT_PUBLIC_API_BASE_URL=${{ steps.get_api_url.outputs.API_URL }}" \
            --timeout=300 \
            --memory=1Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=3

      - name: 'Display Deployment URLs'
        run: |-
          echo "🎉 部署完成！"
          echo "📋 服務網址："
          echo "API 服務: ${{ steps.get_api_url.outputs.API_URL }}"
          CLIENT_URL=$(gcloud run services describe ${{ env.CLIENT_SERVICE_NAME }} --platform=managed --region=${{ env.REGION }} --format='value(status.url)')
          echo "前端服務: ${CLIENT_URL}"